import "./globals.css";
import Header from "@/app/components/Header";
import Sidebar from "@/app/components/Sidebar";
import { DataProvider }from "./context/DataContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <DataProvider>
          <div className="flex h-screen overflow-hidden">
            <Sidebar />
            <div className="flex flex-col flex-1 overflow-auto">
              <div className="max-w-7xl mx-auto w-full">
                <Header />
                <main>{children}</main>
              </div>
            </div>
          </div>
        </DataProvider>
      </body>
    </html>
  );
}
